version: '3.7'
services:
  service_db:
    image: mysql:8.0
    container_name: "devservice_db"
    ports:
      - "127.0.0.1:12202:3306"
    volumes:
      - ./db/current:/var/lib/mysql/
      - ./db/backup:/var/backup
    restart: always
    environment:
      MYSQL_USER: spring_user
      MYSQL_PASSWORD: cvHZL6753xY@
      MYSQL_ROOT_PASSWORD: cvHZL6753xY@

  service_app:
    container_name: "devservice_app"
    build:
      context: ./dockerData
    depends_on:
      - service_db
    ports:
      - "12201:12201"